// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nqptdonqcsitoywmgpqe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5xcHRkb25xY3NpdG95d21ncHFlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY4NjY0NzYsImV4cCI6MjA1MjQ0MjQ3Nn0.TKrC2tnBr5gInBe4J-oN6WyF8NR0SF-avYFeJOGY9jE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);